# Simple workflow for deploying static content to GitHub Pages
name: Deploy page 2

on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - run: npm run test:unit


    - uses: actions/checkout@v3
      with:
        ref: gh-pages
        clean: false
    - name: Push
      run: |
        rm -rf docs/latest && mkdir -p docs/latest && cp -R dist/* docs/latest && sed -i 's/TO_REPLACE_HERE/sidebar\/latest/g' docs/latest/index.html
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add docs/*
        git commit -m "robot commit"
        git push