# Simple workflow for deploying static content to GitHub Pages
name: Deploy Page

on:

  push:
    branches:
      - 'main'
      - 'rc/**'
      - 'releases/**'

  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - run: npm run test:unit

    - uses: actions/checkout@v3
      with:
        ref: gh-pages
        clean: false
    - name: Push
      run: |
        branch=${GITHUB_REF##*/}
        mkdir -p docs
        
        if [ $branch = 'main' ]; then
          cp -R dist/* docs && sed -i 's/TO_REPLACE_HERE/sidebar/g' docs/index.html
        elif [[ $GITHUB_REF == *"refs/tags"* ]]; then
          mkdir -p docs/$branch
          cp -R dist/* docs/$branch && sed -i "s/TO_REPLACE_HERE/sidebar\/$branch/g" docs/$branch/index.html
        else
          mkdir -p docs/beta-$branch
          cp -R dist/* docs/beta-$branch && sed -i "s/TO_REPLACE_HERE/sidebar\/beta-$branch/g" docs/beta-$branch/index.html
        fi

        git config user.name github-actions
        git config user.email github-actions@github.com
        git add docs/*
        git commit -m "robot commit"
        git push